### PR TITLE
only count a year as having an event if we yield event, skip duplicate events

### PR DESCRIPTION
**Pull request by fgregg**
Sometimes there are events that appear in every year we search, so this code handles this.

### CODE REVIEW

**Comment by hancush** [comment]
@fgregg can you say more about why we don't want recurring events? if a board meeting happens annually, i'd want an event for every year. perhaps an example would be illuminating.

**Comment by fgregg** [comment]
we want all types of events, but only want the scraper to emit each individual event once (where an invididual event is equivalent to an event with a unique GUID)

**Comment by hancush** [comment]
@fgregg sure, ok. do you have a sense of why the same event shows up in multiple search years?

**Comment by fgregg** [comment]
That's a deep question that this PR papers over. I'll open up an issue for that. Regardless, I do think that this code is more correct than what it replaces.

**Pull request merged**
