### PR TITLE
Change events scraping to utilize API changes

### PR DESCRIPTION
**Pull request by jmithani**
This PR takes advantages of the addition of the `EventInSiteURL` to event objects in the legistar API. We can now directly visit the associated legistar page, instead of having to link them together by scraping both the API and website in parallel.

This simplifies the code quite a bit, and also makes scraping faster as we have to visit a lot fewer pages and are avoiding all the expensive, non-cacheable POSTs.

Before this PR can be brought it we must adjust the following event scrapers. There are generally more events available in the API than in the website, and the current scrapers take some care to ensure we only scrape events that are available on the website. We will need to ensure that that behavior persists.

- [ ] Chicago
- [ ] LA Metro
- [ ] NYC

# Note
I've picked up this work because the feedback cycles from working on upgrading LA Metro to councilmatic 2.5 were too long.

# Historical 
From @jmithani 

> As noted in #92, the Legistar API is updated to include the `EventInsiteUrl`. This eliminates the need for the web scraper. 

This PR is incomplete, and will be picked up at a later date.

### CODE REVIEW

**Comment by fgregg** [comment]
@hancush NYC requires the old pattern because there's an information elment--Meeting Topic--that **only** appears on the event listing page. 

So, I factored web event related methods into two separate classes and a common base class.

**Comment by hancush** [comment]
@fgregg Nice! I noticed some redundancy in the child classes, but I was having some trouble articulating it, so I took a shot at factoring common functionality into the base class and extending it where necessary. You can see that here: https://github.com/opencivicdata/python-legistar-scraper/compare/change_events_scraping...spike/hec/dry-events

(Not sure how I messed up the git history, but you or I can cherry pick the relevant commits onto this branch, if you're interested in bringing in the changes.)

Let me know what you think!

**Comment by fgregg** [comment]
I'm having a super hard time following the recommendation. Could you possible fix the git history and make a PR against this branch?

**Comment by hancush** [comment]
Happily, @fgregg! Fixed the history in the PR you opened: https://github.com/opencivicdata/python-legistar-scraper/pull/97. Sorry about that, didn't realize it had gotten quite that convoluted.

**Pull request merged**
