### PR TITLE
Legislation

### PR DESCRIPTION
**Pull request by fgregg**
Base methods for legislation scraping

### CODE REVIEW

**Comment by fgregg** [comment]
Oh, also Paul had to pull down these changes in addition to merging.

**Comment by rshorey** [comment]
I think this might be happening automatically now? Will nyc fail if this code didn't get pulled in? I'm running it right now to confirm. If you don't think it'll fail, I'll poke more, but seemed like an easy first test.

**Comment by fgregg** [comment]
if it was not pulled in, then it would fail.

**Comment by rshorey** [comment]
OK, running now, so we will hopefully have confirmation soon, one way or another.

**Pull request merged**
